version: '3'
services:
  iota:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: ash -c "npm run build-index && npm run start"
    ports:
      - '3003:3000'
    volumes:
      - .:/app
